### ISSUE TITLE
EasyBuild 2.0

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-framework#1000]
Current planning: 1st release of 2015. 

 * ~~complete support for easyconfig format v2.0~~ (**postponed**)
 * [x] ~~get rid of deprecated behavior (see https://github.com/hpcugent/easybuild/wiki/Deprecated-functionality)~~ (done, see #1143)
   * [x] ~~includes stop supporting old EasyBuild configuration~~
   * [x] ~~change return type of `EasyBlock.extra_options` to `dict`~~
   * [x] ~~use `self.module_generator` (instead of `self.moduleGenerator`)~~
 * [x] ~~require Python 2.6 (drop support for Python 2.4, support for Py2.4 is deprecated)~~ (done, see #1143)
 * [x] ~~only determine easyblock via software name, don't automatically fall back to `ConfigureMake` (deprecated behaviour)~~ (done, see #1113)
 * ~~make Lmod default modules tool~~ (**too early**)
 * [x] ~~make `--robot` boolean option, specify paths only via `--robot`~~ (handled via`--robot-paths`, see #1080)
 * [x] ~~use `vsc-base` as a proper dependency~~ (done, see PR #1160)
   * [x] ~~enhance bootstrap script to allow testing bootstrap prior to release)~~ (done, see PR #1184)
 * [x] ~~drop support for deprecated functionality in easyblocks~~ (done, see https://github.com/hpcugent/easybuild-easyblocks/pull/547)
 * [x] ~~make framework unit tests more robust, skip the ones relying on non-standard deps or GitHub token, etc.~~ (done, see PR #1167)
   * ~~consider tackling #1097 while at it~~
 * [x] ~~provide a way to auto-fix easyconfigs still relying on deprecated stuff~~ (done, see PR #1151)
 * [x] ~~reinstate support for downloading over a proxy~~ (done, see #1150)
 * [x] ~~fix basic support for Linux@POWER~~ (done, see PR #1044)
 * [x] ~~try to get rid of (deprecation) warning messages~~ (done, see https://github.com/hpcugent/vsc-base/pull/155)
 * [x] ~~fix bug with `hiddendependencies` when `--force` is used~~ (done, see PR #1161)
 * [x] ~~default system config file locations(s)~~ (done, see PR #1166)
 * [x] ~~stop updating Lmod user cache by default, only to then ignore it completely~~ (done, see PR #1185)
 * [x] ~~also consider robot search path when looking for specified easyconfigs~~  (done, see PR #1201)

required documentation updates:

* [x] ~~update development setup w.r.t. vsc-base dep~~ (done, see https://github.com/hpcugent/easybuild/pull/90)
* [x] ~~update requires dependencies to mention vsc-base~~ (done, see https://github.com/hpcugent/easybuild/pull/88)
* [x] ~~configuring and running the (framework) unit tests~~ (done, see https://github.com/hpcugent/easybuild/pull/89)
  * ~~definitely mention $TEST_EASYBUILD_MODULES_TOOL~~
* [x] ~~update docs w.r.t. taking robot search path into account for both specified easyconfigs and resolving deps~~ (done, see https://github.com/hpcugent/easybuild/pull/92)
* [x] ~~move contents of Deprecated-functionality.html to No-longer-support-functionality.html~~ (done, see https://github.com/hpcugent/easybuild/pull/91)
* [x] ~~document usage of fix-broken-easyconfigs.py script~~ (done, see https://github.com/hpcugent/easybuild/pull/91)
* [x] ~~document --from-pr (incl. specified easyconfigs)~~ (done, see https://github.com/hpcugent/easybuild/pull/92)
* [x] ~~update docs w.r.t. download-over-proxy support~~ (done, see https://github.com/hpcugent/easybuild/pull/98)

postponed to EasyBuild v2.1:

 * add support for `--review-pr` (see PR #1142)
 * deprecate `log.error` and `log.exception` (see PR #1183)

**Comment by boegel** [comment]
big step towards EasyBuild v2.0 @ https://github.com/hpcugent/easybuild-framework/pull/1160

**Comment by boegel** [comment]
EasyBuild v2.0 is released

issue for tracking progress towards EasyBuild v2.1 @ https://github.com/hpcugent/easybuild/issues/100 (no, I didn't game the issue number)
